default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: j3
  password: password

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
  database: my_app_production
  username: my_app
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>